### ISSUE TITLE
Crash opening app on Android 5.1.1

### ISSUE THREAD

**Issue by Twinklebear** [Gwindow/WhatAndroid#48]
Stack trace from the crash report:
```
Error Report on: Mon Mar 28 20:20:08 PDT 2016
what.whatandroid version name: 2.1.5.b, version code: 26
Android Version: 5.1.1
Device: A0001
Brand: oneplus
Model: A0001

Stack Trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{what.whatandroid/what.whatandroid.profile.ProfileActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class android.widget.ListView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class android.widget.ListView
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at what.whatandroid.navdrawer.NavigationDrawerFragment.onCreateView(NavigationDrawerFragment.java:86)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at what.whatandroid.profile.ProfileActivity.onCreate(ProfileActivity.java:49)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
... 10 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:607)
... 36 more
Caused by: android.content.res.Resources$NotFoundException: Resource "what.whatandroid:color/Background" (7f0b0005)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0b0005 a=-1 r=0x7f0b0005}
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2588)
at android.content.res.Resources.loadDrawable(Resources.java:2528)
at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
at android.view.View.<init>(View.java:3746)
at android.view.ViewGroup.<init>(ViewGroup.java:498)
at android.widget.AdapterView.<init>(AdapterView.java:243)
at android.widget.AbsListView.<init>(AbsListView.java:808)
at android.widget.ListView.<init>(ListView.java:151)
at android.widget.ListView.<init>(ListView.java:147)
at android.widget.ListView.<init>(ListView.java:143)
... 39 more

Please describe where this occurred and what may have provoked the crash to help debug the issue:

Installed updated app and now app crashes during log in procedure.
```

@stuxo thoughts on this? I actually did not test on a 5.1.1 emulator, but it looks like some issues with the theme background color.

**Comment by stuxo** [comment]
@Twinklebear I'll have to run it on an emulator and see whats going on.

**Comment by Twinklebear** [comment]
Let me know if you want me to add you to the whatandroid crash report forwarding as well, when the app crashes it saves the stack trace + some device version info and prompts the user if they want to email the account the next time they start the app.

**Comment by stuxo** [comment]
I can't reproduce the issue on an emulated Nexus 6 running 5.1.1 using my local debug build.

**Comment by Twinklebear** [comment]
Interesting, I got another report from a user also running a One Plus device, I wonder if it's just these devices? I'll try it out some as well.

```
Error Report on: Tue Mar 29 12:26:37 JST 2016
what.whatandroid version name: 2.1.5.b, version code: 26
Android Version: 5.1.1
Device: OnePlus2
Brand: OnePlus
Model: ONE A2001

Stack Trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{what.whatandroid/what.whatandroid.profile.ProfileActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class android.widget.ListView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2354)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5300)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class android.widget.ListView
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at what.whatandroid.navdrawer.NavigationDrawerFragment.onCreateView(NavigationDrawerFragment.java:86)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1332)
at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2288)
at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at what.whatandroid.profile.ProfileActivity.onCreate(ProfileActivity.java:49)
at android.app.Activity.performCreate(Activity.java:6088)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
... 10 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:607)
... 36 more
Caused by: android.content.res.Resources$NotFoundException: Resource "what.whatandroid:color/Background" (7f0b0005)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0b0005 a=-1 r=0x7f0b0005}
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2464)
at android.content.res.Resources.loadDrawable(Resources.java:2404)
at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
at android.view.View.<init>(View.java:3743)
at android.view.ViewGroup.<init>(ViewGroup.java:498)
at android.widget.AdapterView.<init>(AdapterView.java:243)
at android.widget.AbsListView.<init>(AbsListView.java:808)
at android.widget.ListView.<init>(ListView.java:151)
at android.widget.ListView.<init>(ListView.java:147)
at android.widget.ListView.<init>(ListView.java:143)
... 39 more

Please describe where this occurred and what may have provoked the crash to help debug the issue:

Appears to login successfully, and crashes when switching to next screen.
```

**Comment by stuxo** [comment]
I can reproduce it with the release build. Perhaps obfuscation or your build environment is causing the resources to not be generated correctly

**Comment by Twinklebear** [comment]
Ah that's not good, maybe something is not configured properly in the release build with the theme changes? I'm not sure.

**Comment by Twinklebear** [comment]
It seems like the theme info isn't set up how we expect it to be by the compat library so we don't load values-night or values-notnight and so fail to find the "Background" color resource since it's only defined in those two. For now I've pasted the notnight theme colors into values/colors.xml so that something exists to pick by default if the theme isn't properly set up in 65dd2e6
