### ISSUE TITLE
Opening download directory selection browser crashes on Android 6.0

### ISSUE THREAD

**Issue by Twinklebear** [Gwindow/WhatAndroid#50]
Opening the download directory chooser crashes on Android 6.0, @stuxo mentions this may be due to needing to request permissions to browse the directories now.

The browser also missed out on getting theme'd and should be restyled to match as well

Crash report:

```
Error Report on: Tue Mar 29 23:00:24 MDT 2016
what.whatandroid version name: 2.1.6.b, version code: 27
Android Version: 6.0.1
Device: shamu
Brand: google
Model: Nexus 6

Stack Trace:
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:337)
at android.widget.ListView.setAdapter(ListView.java:491)
at what.whatandroid.settings.FolderPickerDialog.onCreateDialog(FolderPickerDialog.java:119)
at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Please describe where this occurred and what may have provoked the crash to help debug the issue:
```

**Comment by Twinklebear** [comment]
One user tested manually granting the "Storage permission" to the app and opening this no longer crashed, so it's definitely that we're not requesting the right permissions.

**Comment by stuxo** [comment]
I thought that might have been the case. Its an annoying addition to android 6.0
